services:
  - type: web
    name: cv-react-final
    env: node
    region: ohio
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview -- --port 10000"
    plan: free
